library(tidyverse)
library(skimr)
library(lubridate)
library(readr)
library(prophet)
df <- read_csv("Analysis/cleaned_new-_1_.csv")
z_score <- c((df$y-mean(df$y))/sd(df$y))
y<-z_score
dF = data.frame(df$ds,y)
DF <- dF %>% rename(ds=df.ds)
df_<- DF %>% filter(y< 3) 
m<-prophet(df_)
future<-make_future_dataframe(m,periods=365)
head(future)
forecast <- predict(m,future)
#bias(df,forecast)
head(forecast)
plot(m,forecast)
